export const policies = {
  AbpIdentityRoles: 'AbpIdentity.Roles',
  AbpIdentityRolesCreate: 'AbpIdentity.Roles.Create',
  AbpIdentityRolesUpdate: 'AbpIdentity.Roles.Update',
  AbpIdentityRolesDelete: 'AbpIdentity.Roles.Delete',
  AbpIdentityRolesManagePermissions: 'AbpIdentity.Roles.ManagePermissions',
  AbpIdentityUsers: 'AbpIdentity.Users',
  AbpIdentityUsersCreate: 'AbpIdentity.Users.Create',
  AbpIdentityUsersUpdate: 'AbpIdentity.Users.Update',
  AbpIdentityUsersDelete: 'AbpIdentity.Users.Delete',
  AbpIdentityUsersGet: 'AbpIdentity.Users.Get',
  AbpIdentityUsersManagePermissions: 'AbpIdentity.Users.ManagePermissions',
  AbpIdentityUserLookup: 'AbpIdentity.UserLookup',
  FeatureManaementManageHostFeatures: 'FeatureManagement.ManageHostFeatures',
  SettingManagementEmailing: 'SettingManagement.Emailing', 
  AbpTenantManagementTenants: 'AbpTenantManagement.Tenants',
  AbpTenantManagementTenantsCreate: 'AbpTenantManagement.Tenants.Create',
  AbpTenantManagementTenantsUpdate: 'AbpTenantManagement.Tenants.Update',
  AbpTenantManagementTenantsDelete: 'AbpTenantManagement.Tenants.Delete',
  AbpTenantManagementTenantsManageFeatures: 'AbpTenantManagement.Tenants.ManageFeatures',
  AbpTenantManagementTenantsManageConnectionStrings: 'AbpTenantManagement.Tenants.ManageConnectionStrings',
  
  Courses: 'Courses',
  CoursesGet: 'Courses.Get',
  CoursesGetAll: 'Courses.GetAll',
  CoursesCreate: 'Courses.Create',
  CoursesUpdate: 'Courses.Update',
  CoursesDelete: 'Courses.Delete',
  CoursesStudents: 'Courses.Students',

  Rules: 'Rules',
  RulesGet: 'Rules.Get',
  RulesGetAll: 'Rules.GetAll',
  RulesCreate: 'Rules.Create',
  RulesUpdate: 'Rules.Update',
  RulesDelete: 'Rules.Delete',
  
  DcpReports: 'DcpReports',
  CreateNewDcpReport: 'DcpReports.CreateNewDcpReport',
  GetDcpReportApprovalHistory: 'DcpReports.GetDcpReportApprovalHistory',
  DcpReportApproval: 'DcpReports.DcpReportApproval',
  GetMyDcpReport: 'DcpReports.GetMyDcpReport',
  RemoveDcpReport: 'DcpReports.RemoveDcpReport',
  GetDcpReportDetail: 'DcpReports.GetDcpReportDetail',
  GetDcpReportDetailApproval: 'DcpReports.GetDcpReportDetailApproval',
  UpdateDcpReport: 'DcpReports.UpdateDcpReport',
  
  LRReports: 'LRReports',
  CreateNewLRReport: 'LRReports.CreateNewLRReport',
  GetLRApprovalHistory: 'LRReports.GetLRApprovalHistory',
  LRReportApproval: 'LRReports.LRReportApproval',
  GetMyLRReport: 'LRReports.GetMyLRReport',
  RemoveLRReport: 'LRReports.RemoveLRReport',
  GetLRReportDetail: 'LRReports.GetLRReportDetail',
  GetLRReportDetailApproval: 'LRReports.GetLRReportDetailApproval',
  UpdateLRReport: 'LRReports.UpdateLRReport',

  Rankings: 'Rankings',
  Statistics: 'Statistics',

  AssignDcpReport: 'AssignDcpReport',
  AssignLessonRegisterReport: 'AssignLessonRegisterReport',
  GetScheduleList: 'GetScheduleList',
  GetMyAssignedSchedule: 'GetMyAssignedSchedule',
};